spring:
  profiles:
    active: local
  application:
    name: batch
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8181
  jetty:
    acceptors: 10
    selectors: 10
  context-path: /monitor


batch:
  home: /work/manjin/project/batch/src/main/resources/
  id: test
  router: net.mj.camel.batch.router.db.DBBatchRouter


logging.level.org.eclipse.jetty: INFO
logging.level.org.springframework: INFO
logging.level.org.springframework.web: INFO
logging.level.org.hibernate: INFO
logging:
  pattern:
    console: "%d{yyyy:MM:dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{35} : %msg %n"


---
#local 환경
spring:
  profiles: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/batch?serverTimezone=UTC&useSSL=false
    username: root
    password: 3134
    dbcp2:
      max-total: 10

  jpa:
    properties:
      hibernate.jdbc.batch_size: 100

batch:
  home: /work/manjin/project/batch/src/main/resources/

